amcl:
  ros__parameters:
    FollowPath:
      # plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      # allow_reversing: true
      # use_rotate_to_heading: true
      # rotate_to_heading_min_angle: 0.4      # rad, try 0.2–0.6
      # rotate_to_heading_angular_vel: 1.0    # rad/s
      # min_approach_linear_velocity: 0.05    # don’t force stop too early
      # lookahead_dist: 0.5                    # tune; too small can oscillate
      # regulated_linear_scaling_min_radius: 
      0.6
      # regulated_linear_scaling_min_speed: 0.05    
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.15
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.125
      movement_time_allowance: 5.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    FollowPath:
      plugin: nav2_graceful_controller::GracefulController
      transform_tolerance: 0.1
      min_lookahead: 0.25
      max_lookahead: 1.0
      initial_rotation: true
      initial_rotation_threshold: 0.75
      prefer_final_rotation: true
      allow_backward: True
      k_phi: 2.0
      k_delta: 1.0
      beta: 0.4
      lambda: 2.0
      v_linear_min: 0.05
      v_linear_max: 0.3
      v_angular_max: 2.0
      v_angular_min_in_place: 0.25
      slowdown_radius: 0.5

    
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    
    
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      #robot_radius: 0.125
      # Footprint points are ordered clockwise starting from front-left corner
      footprint:
        "[[-0.120, 0.081]
          [-0.120, -0.081]
          [-0.038, -0.081]
          [-0.038, -0.1125]
          [0.042, -0.1125]
          [0.042, 0.1125]
          [-0.038, 0.1125]
          [-0.038, 0.081]]"
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.35
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 5.0 #  <-- was 3.0
          raytrace_min_range: 0.15
          obstacle_max_range: 2.5
          obstacle_min_range: 0.15
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.125
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.20
          obstacle_max_range: 2.5
          obstacle_min_range: 0.25
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.3
      always_send_full_costmap: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
      simulate_ahead_time: 2.0
      max_rotational_vel: 1.0
      min_rotational_vel: 0.1
      rotational_acc_lim: 3.2
    backup:
      plugin: "nav2_behaviors::BackUp"
      simulate_ahead_time: 2.0
      backup_dist: 0.3
      backup_speed: 0.1
      time_allowance: 10.0
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
      simulate_ahead_time: 2.0
      speed: 0.1
      time_allowance: 10.0
    wait:
      plugin: "nav2_behaviors::Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 10
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.26, 0.0, 1.0]
    min_velocity: [-0.26, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odometry/filtered"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

map_server:
  ros__parameters:
    frame_id: "map"
    topic_name: "map"
    use_sim_time: False
    # yaml_filename: "/home/gruppe-6/ros2/ws/src/maps/Datalab.yaml"
    #lagt til
    # QoS settings to keep map available for late subscribers
    qos_overrides:
      /map:
        publisher:
          durability: transient_local
          reliability: reliable

collision_monitor:
  ros__parameters:
    enabled: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 1.0
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    enable_stamped_cmd_vel: False # False for Jazzy or older by default

    # polygons: ["PolygonStop", "PolygonSlow"]
    # PolygonStop:
    #   type: "circle"
    #   radius: 0.15
    #   # points: "[[0.4, 0.3], [0.4, -0.3], [0.0, -0.3], [0.0, 0.3]]"
    #   action_type: "stop"
    #   min_points: 4  # max_points: 3 for Humble
    #   visualize: True
    #   polygon_pub_topic: "polygon_stop"
    # PolygonSlow:
    #   type: "circle"
    #   radius: 0.5
    #   # points: "[[0.6, 0.4], [0.6, -0.4], [0.0, -0.4], [0.0, 0.4]]"
    #   action_type: "slowdown"
    #   min_points: 4  # max_points: 3 for Humble
    #   slowdown_ratio: 1.0
      
    #   visualize: True
    #   polygon_pub_topic: "polygon_slowdown"

    polygons: ["VelocityPolygonStop"]
    VelocityPolygonStop:
      type: "velocity_polygon"
      action_type: "stop"
      min_points: 6
      visualize: True
      enabled: True
      polygon_pub_topic: "velocity_polygon_stop"
      velocity_polygons: ["rotation", "translation_forward", "translation_backward", "stopped"]
      holonomic: false
      rotation:
        points: "[[120e-3, 115e-3], [-150e-3, 115e-3], [-150e-3, -115e-3], [120e-3, -115e-3]]"
        linear_min: 0.0
        linear_max: 0.05
        theta_min: -1.0
        theta_max: 1.0
      translation_forward:
        points: "[[200e-3, 115e-3], [-150e-3, 115e-3], [-150e-3, -115e-3], [200e-3, -115e-3]]"
        linear_min: 0.0
        linear_max: 0.3
        theta_min: -1.0
        theta_max: 1.0
      translation_backward:
        points: "[[102e-3, 115e-3], [-150e-3, 115e-3], [-150e-3, -115e-3], [102e-3, -115e-3]]"
        linear_min: -0.3
        linear_max: 0.0
        theta_min: -1.0
        theta_max: 1.0
      # This is the last polygon to be checked, it should cover the entire range of robot's velocities
      # It is used as the stopped polygon when the robot is not moving and as a fallback if the velocity
      # is not covered by any of the other sub-polygons
      stopped:
        points: "[[42e-3, 110e-3], [-120e-3, 110e-3], [-120e-3, -110e-3], [42e-3, -110e-3]]"
        linear_min: -0.3
        linear_max: 0.3
        theta_min: -1.0
        theta_max: 1.0
    
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"

docking_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 50.0
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names: ['controller_server', 'planner_server', 'behavior_server', 
                 'bt_navigator', 'velocity_smoother', 'collision_monitor']
                 
#'waypoint_follower','route_server', 
lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names: ['map_server', 'amcl']
