ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: false
    base_link_frame: base_link
    odom_frame: odom
    world_frame: odom
    publish_tf: true

    # Your IMU topic and frame
    imu0: /imu/data
    imu0_config: [false, false, false,   # x y z position
                  false, false, false,   # roll pitch yaw (pose)
                  false, false, false,   # x y z linear velocity
                  true,  true,  true]    # roll pitch yaw rates
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
